
include: package:flutter_lints/flutter.yaml

linter:

  rules:
  

    # Style rules 

    library_names: true
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    avoid_empty_else: true
    unnecessary_brace_in_string_interps: true
    avoid_redundant_argument_values: true
    leading_newlines_in_multiline_strings: true
    always_put_control_body_on_new_line: true
    avoid_unnecessary_containers: true
    empty_catches: true
    # formatting
    lines_longer_than_80_chars: false
    curly_braces_in_flow_control_structures: true
    prefer_single_quotes: true
    camel_case_extensions: true
    camel_case_types: true

    # doc comments
    slash_for_doc_comments: true
    sort_pub_dependencies: true
    # error rules
    always_use_package_imports: true
    avoid_dynamic_calls: false
    avoid_print: true  # Uncomment to disable the `avoid_print` rule
    require_trailing_commas: true
    prefer_const_declarations: true
    avoid_relative_lib_imports: true
    avoid_type_to_string: true
    empty_statements: true
    hash_and_equals: true
    control_flow_in_finally: true
    prefer_void_to_null: true
    unrelated_type_equality_checks: true



    
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule

